const ActionsTypes = {
	LOAD_NOTES_REQUEST: 'LOAD_NOTES_REQUEST',
	LOAD_NOTES_SUCCESS: 'LOAD_NOTES_SUCCESS',
	LOAD_NOTES_FAIL: 'LOAD_NOTES_FAIL',
	ADD_ITEM: 'ADD_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	EDIT_ITEM: 'EDIT_ITEM'
};

export default ActionsTypes;